import { GoogleGenAI } from '@google/genai';

// Initialize Gemini client server-side
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

export interface ConversationMessage {
  role: 'user' | 'assistant';
  text: string;
}

const MODELS_TO_TRY = ['gemini-3.5-flash-lite', 'gemini-3.1-flash-lite', 'gemini-3.5-flash', 'gemini-3.7-flash'];

async function generateContentWithFallback(params: any): Promise<any> {
  let lastError = null;
  for (const model of MODELS_TO_TRY) {
    try {
      // Add an 8-second timeout per attempt to ensure telephone calls never hang
      const timeoutPromise = new Promise((_, reject) =>
        setTimeout(() => reject(new Error(`Model ${model} timed out after 8s`)), 8000)
      );

      const generatePromise = ai.models.generateContent({
        ...params,
        model,
      });

      const res = await Promise.race([generatePromise, timeoutPromise]);
      return res;
    } catch (err: any) {
      lastError = err;
      console.warn(`Model ${model} attempt failed: ${err.message}, trying fallback...`);
    }
  }
  throw lastError;
}

const DEFAULT_SYSTEM_PROMPT = `אתה עוזר קולי חכם, אדיב ותמציתי הפועל בשיחת טלפון קולית (עבור משתמשים בטלפונים כשרים ללא אינטרנט).
הנחיות חשובות מאוד למענה בשיחת טלפון:
1. ענה בעברית ברורה, טבעית ומכבדת.
2. מכיוון שהתשובה תושמע כהקלטה קולית בטלפון, ענה בתמציתיות ובפשטות (משפט עד שלושה משפטים עיקריים, אלא אם התבקשת לפרט).
3. אל תשתמש בסימוני עיצוב כמו כוכביות, כותרות, נקודות בולטות, קישורים או אימוג'ים - אלא בטקסט רציף המתאים להקראה קולית.
4. אם השאלה לא ברורה או ההקלטה קטועה, בקש בנימוס לחזור על השאלה.
5. תן מידע מדויק וענייני.
6. חשוב מאוד: לעולם אל תוסיף בסיום דבריך שאלות או הצעות המשך כגון "האם תרצה לשאול עוד משהו?", "תרצה עוד תרגיל?", "איך אוכל לעזור עוד?" או "האם להסביר שוב?". סיים ישירות בתשובה עצמה ללא שאלות פתוחות בסוף, כי מערכת הטלפון משמיעה בעצמה הנחיה לשאלה הבאה.
7. זכור תמיד את כל השלבים והתשובות שניתנו בשיחה הנוכחית. אם המשתמש שואל שאלת המשך כגון "תכפיל ב-3", "תחזור על התשובה הקודמת", "למה?", או "כמה זה ביחד?", התייחס ישירות לתוצאות ולדברים שנאמרו קודם לכן בשיחה והמשך את החישוב או ההסבר ברציפות.`;

/**
 * Strips closing conversational questions generated by the AI
 */
export function cleanSpokenResponse(text: string): string {
  if (!text) return '';
  let cleaned = text.trim();
  
  // Remove markdown symbols
  cleaned = cleaned.replace(/[*#_~`>]/g, ' ');
  
  // Remove conversational closing questions added by LLM
  cleaned = cleaned
    .replace(/(האם\s+)?(תרצה|רוצה|מעוניין|תרצו|רוצים|היית רוצה)\s+(לשאול|לדעת|לפתור|לקבל|לשמוע|לתרגל|שאסביר|שאעזור|עוד).*?\??$/gi, '')
    .replace(/(האם\s+)?(יש לך|יש עוד|ישנן)\s+(שאלה|שאלות|משהו נוסף|דבר נוסף).*?\??$/gi, '')
    .replace(/(איך|כיצד)\s+(אוכל|אפשר|נוכל)\s+(לעזור|לסייע)\s+(עוד|נוסף|לך).*?\??$/gi, '')
    .replace(/(אשמח|נשמח)\s+(לענות|לעזור|לסייע|לפתור).*?\??$/gi, '')
    .replace(/\s+/g, ' ')
    .trim();

  return cleaned;
}

export interface AudioQueryResult {
  textResponse: string;
  transcript?: string;
  emailAction?: {
    isEmailRequest: boolean;
    targetEmail?: string;
    emailContent?: string;
    subject?: string;
  };
}

/**
 * Process spoken audio from telephone caller and generate a spoken response.
 */
export async function processAudioQuery(
  audioBuffer: Buffer,
  mimeType: string,
  history: ConversationMessage[] = [],
  customSystemPrompt?: string
): Promise<AudioQueryResult> {
  try {
    const base64Audio = audioBuffer.toString('base64');
    const systemInstruction = customSystemPrompt || DEFAULT_SYSTEM_PROMPT;

    // Build multi-turn contents including prior conversation history
    const contents: any[] = [];

    // Add prior conversation turns so Gemini has full context and memory of previous calculations and statements
    if (Array.isArray(history) && history.length > 0) {
      for (const msg of history) {
        if (msg && msg.text && msg.text.trim()) {
          contents.push({
            role: msg.role === 'assistant' ? 'model' : 'user',
            parts: [{ text: msg.text }],
          });
        }
      }
    }

    // Add current audio query as the latest user turn
    const contextPrompt = `האזן להקלטה הקולית הזו של המשתמש בטלפון, בהמשך ישיר לשיחה שהתקיימה עד כה.
בצע את המשימות הבאות:
1. זהה במדויק מה המשתמש שאל או אמר בעברית (כולל שאלות המשך, חישובים, או פקודות לשלוח חומר/סיכום/מתכון/תשובות למייל).
2. אם המשתמש מבקש לשלוח חומר למייל ומקריא כתובת אימייל (למשל "שלח למייל ישראל שטרודל ג'ימייל נקודה קום", "m0583277004@gmail.com", "israel@gmail.com" וכו'):
   - פענח ותרגם את כתובת האימייל בצורה תקנית ומדויקת באנגלית (המר "שטרודל" או "כרוכית" או "at" ל-@, המר "נקודה" ל-., תקן שגיאות שמיעה נפוצות).
   - נסח כותרת ותוכן מלא, מסודר ומפורט שנשלח במייל (למשל כל סיכום השיחה עד כה, או המתכון/התשובה שהתבקשה).
   - נסח תשובה קולית קצרה ומרגיעה בטלפון המאשרת שהמייל נשלח לכתובת שפורשה (לדוגמה: "שלחתי כעת את המידע לכתובת ישראל שטרודל ג'ימייל נקודה קום.").
3. אם זו שאלה רגילה - נסח תשובה קולית קצרה, ברורה ומדויקת בעברית בהתבסס על היסטוריית השיחה.

פורמט התשובה שלך חייב להיות אך ורק במבנה הבא:
[TRANSCRIPT]: תמלול השאלה של המשתמש
[EMAIL_TARGET]: כתובת_אימייל_תקנית_אם_התבקשה_או_NONE
[EMAIL_SUBJECT]: נושא_המייל_אם_יש_או_NONE
[EMAIL_BODY]: תוכן_המייל_המפורט_אם_יש_או_NONE
[ANSWER]: התשובה המדויקת שתושמע למשתמש בטלפון`;

    contents.push({
      role: 'user',
      parts: [
        {
          inlineData: {
            mimeType: mimeType || 'audio/wav',
            data: base64Audio,
          },
        },
        {
          text: contextPrompt,
        },
      ],
    });

    const response = await generateContentWithFallback({
      contents,
      config: {
        systemInstruction,
        temperature: 0.2,
      },
    });

    const responseText = response.text || '';
    
    // Parse out tags
    let transcript = '';
    let answer = responseText;
    let emailTarget = '';
    let emailSubject = '';
    let emailBody = '';

    if (responseText.includes('[TRANSCRIPT]:')) {
      const matchTranscript = responseText.match(/\[TRANSCRIPT\]:\s*(.*?)(?=\n\[|$)/s);
      if (matchTranscript) transcript = matchTranscript[1].trim();
    }

    if (responseText.includes('[EMAIL_TARGET]:')) {
      const matchTarget = responseText.match(/\[EMAIL_TARGET\]:\s*(.*?)(?=\n\[|$)/s);
      if (matchTarget) {
        const val = matchTarget[1].trim();
        if (val && !val.includes('NONE') && val.includes('@')) {
          emailTarget = val.replace(/[<>]/g, '').trim();
        }
      }
    }

    if (responseText.includes('[EMAIL_SUBJECT]:')) {
      const matchSubject = responseText.match(/\[EMAIL_SUBJECT\]:\s*(.*?)(?=\n\[|$)/s);
      if (matchSubject && !matchSubject[1].includes('NONE')) {
        emailSubject = matchSubject[1].trim();
      }
    }

    if (responseText.includes('[EMAIL_BODY]:')) {
      const matchBody = responseText.match(/\[EMAIL_BODY\]:\s*(.*?)(?=\n\[|$)/s);
      if (matchBody && !matchBody[1].includes('NONE')) {
        emailBody = matchBody[1].trim();
      }
    }

    if (responseText.includes('[ANSWER]:')) {
      const matchAnswer = responseText.match(/\[ANSWER\]:\s*(.*?)$/s);
      if (matchAnswer) {
        answer = matchAnswer[1].trim();
      }
    } else {
      // Fallback cleanup if tags weren't exact
      answer = responseText
        .replace(/\[TRANSCRIPT\]:.*?\n/g, '')
        .replace(/\[EMAIL_TARGET\]:.*?\n/g, '')
        .replace(/\[EMAIL_SUBJECT\]:.*?\n/g, '')
        .replace(/\[EMAIL_BODY\]:.*?\n/g, '')
        .replace(/\[ANSWER\]:/g, '')
        .trim();
    }

    const emailAction = emailTarget
      ? {
          isEmailRequest: true,
          targetEmail: emailTarget,
          emailContent: emailBody || answer,
          subject: emailSubject || 'מידע משיחה קולית - ימות המשיח AI',
        }
      : undefined;

    return {
      textResponse: cleanSpokenResponse(answer) || 'שלום, קיבלתי את שאלתך.',
      transcript: transcript || 'שאלה קולית שהוקלטה בטלפון',
      emailAction,
    };
  } catch (error: any) {
    console.error('Error in Gemini audio processing:', error);
    // Fallback message
    return {
      textResponse: 'מצטערים, חלה שגיאה בעיבוד השאלה הקולית. אנא נסה שוב.',
      transcript: 'שגיאה בעיבוד האודיו',
    };
  }
}

/**
 * Process text query with context history
 */
export async function processTextQuery(
  textPrompt: string,
  history: ConversationMessage[] = [],
  customSystemPrompt?: string
): Promise<{ textResponse: string }> {
  try {
    const systemInstruction = customSystemPrompt || DEFAULT_SYSTEM_PROMPT;

    const chatContents = history.map((msg) => ({
      role: msg.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: msg.text }],
    }));

    chatContents.push({
      role: 'user',
      parts: [{ text: textPrompt }],
    });

    const response = await generateContentWithFallback({
      contents: chatContents,
      config: {
        systemInstruction,
        temperature: 0.5,
      },
    });

    return {
      textResponse: cleanSpokenResponse(response.text || '') || 'שלום, קיבלתי את פנייתך.',
    };
  } catch (error: any) {
    console.error('Error in Gemini text processing:', error);
    return {
      textResponse: 'חלה שגיאה זמנית בעיבוד השאלה. אנא נסו שוב עוד רגע.',
    };
  }
}
